version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: fastapi.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "C:/Users/sriva/Downloads/Multimedia Data:/data"
    env_file:
      - .env

  streamlit:
    build:
      context: .
      dockerfile: streamlit.Dockerfile
    ports:
      - "8501:8501"

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourpassword
      - N8N_SECURE_COOKIE=false
      - DB_SQLITE_POOL_SIZE=5
      - N8N_RUNNERS_ENABLED=true
      - EXPRESS_TRUST_PROXY=true   
      - WEBHOOK_URL=${PUBLIC_BASE_URL}  

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"   
    depends_on:
      - fastapi
      - streamlit
      - n8n
